### ISSUE TITLE
Thread sleeping location

### ISSUE THREAD

**Issue by cszuo** [pd0wm/airtag-dump#1]
Thank you for this cool project, it is really inspiring.

While reading the code, I noticed this sleep instruction:
https://github.com/pd0wm/airtag-dump/blob/master/src/main.rs#L61
You put it before the actual glitching, and direct dump firmware after sending glatch command without waiting for the glitch.
Should there be a sleep instruction after sending a glitch command to wait for the glitching?

BTW: how long should I expect to get a success glitching? Mine has run for more than an hour still no success. I have tried to add the sleep instruction, but still no success.

**Comment by pd0wm** [comment]
That 50 ms is a wait after turning off the target power. This gives it some time to completely drain all caps before the next glitch attempt. I didn't need to wait after the glitching, but maybe if you're using a different programmer you can add a small sleep. I'm using a J-Link. For me it usually takes about 5 minutes to get some results, but the read doesn't always succeed.

What error message are you getting on unsuccessful glitch attempts? You should get something along the lines of `Other(AP 0 is not a memory AP)` indicating it's protected. Otherwise you might have other connection issues.

Since you technically need a level shifter to correctly measure the 1.8 V trigger input, your timing might be different than mine. Try using an oscilloscope, and make sure your glitch us about 20us before the drop in core voltage. See https://pbs.twimg.com/media/E1hgeRHX0AEp4Ao?format=jpg&name=large.

**Comment by cszuo** [comment]
Thank you for the explanation. 
I tried both J-Link and ST-Link. I was using a J-Link, but it is not the typical one. It is a build-in functionality provided by Nordic PCA10056 board to program other nRF52 boards. It worked for other nRF52832 boards, but it is not stable for airtag. Sometimes it shows the error “Other(AP 0 is not a memory AP)”, but sometimes other errors. So I have to use the ST-Link. The error it shows is “Probe(CommandNotSupportedByProbe)”, and I have confirmed that a protected nRF52832 chip will cause this error for the ST-Link in my case. So I assume it works.

I am a pure software guy, do not know much about hardware and I don’t have an oscilloscope. So I am trying to use all the parameters you have used. With your parameters (especially 19500 delay), do I need a level shifter? Here is the connections of my setup. Please let me know if it does not look correct to you (the n-mosfet is NTE2984). Thank you.

![dump airtag](https://user-images.githubusercontent.com/8746324/119045694-cb748000-b989-11eb-82b2-828348028bf7.jpg)

**Comment by pd0wm** [comment]
I also get different errors than the `AP 0 is not a memory AP` sometimes, but it's that error in ~95% of cases.

I did not use a level shifter, which is why you probably need to tune the `19500` a bit for your specific hardware. The rise time of the 1.8V is pretty slow, and it will be a bit arbitrary when it will read as a logic high. You can also try looping over different values and hope you get lucky, but an oscilloscope is really the way to go. An oscilloscope is also good to verify your glitch works as intended, however the FET you used looks suitable.

**Comment by cszuo** [comment]
Thank you. I have tried to change the 19500 from 15000 to 46000 (100 each step) and didn't succeed. As you said, I need an oscilloscope, it can tell where is the problem. So I have placed orders on a level shifter and oscilloscope. I will send updates later.

**Comment by cszuo** [comment]
I have located the problem. It is the delay value. The oscilloscope is very useful. With its help, I found the proper delay value for my hardware set, and the value is `23700`. Thank you for the suggestion of the oscilloscope.

**Comment by itewqq** [comment]
> I have located the problem. It is the delay value. The oscilloscope is very useful. With its help, I found the proper delay value for my hardware set, and the value is `23700`. Thank you for the suggestion of the oscilloscope.

 @cszuo Hey cszuo, have you successfully dumped the airtag firmware? I used the same configuration as yours but my stm32 will always be stuck...

**Comment by cszuo** [comment]
> > I have located the problem. It is the delay value. The oscilloscope is very useful. With its help, I found the proper delay value for my hardware set, and the value is `23700`. Thank you for the suggestion of the oscilloscope.
> 
> @cszuo Hey cszuo, have you successfully dumped the airtag firmware? I used the same configuration as yours but my stm32 will always be stuck...

Yes, I have dumped the firmware. You need to change the value for your hardware which includes the stm32 and computer. Because I noticed that, the value may change for different computers. It will be much easier if you can observe it through oscilloscope.

**Comment by itewqq** [comment]
> > > I have located the problem. It is the delay value. The oscilloscope is very useful. With its help, I found the proper delay value for my hardware set, and the value is `23700`. Thank you for the suggestion of the oscilloscope.
> > 
> > 
> > @cszuo Hey cszuo, have you successfully dumped the airtag firmware? I used the same configuration as yours but my stm32 will always be stuck...
> 
> Yes, I have dumped the firmware. You need to change the value for your hardware which includes the stm32 and computer. Because I noticed that, the value may change for different computers. It will be much easier if you can observe it through oscilloscope.

Thank you so much for replying to me! 

Although I still couldn't get this program to run on stm32 (_Every time I run my stm32 it will be stuck immediately. I don't know if it has anything to do with the version of rust. I use stm32f103c8t6. As for another stmf103c6t6 board, when I burn it into airtag-dump, it can't connect with my computer at all_), I wrote my own glitch code based on Raspberry Pi. My glitch looks like this on the oscilloscope (red arrow):

![image](https://user-images.githubusercontent.com/30570177/121982494-2bf8b080-cdc2-11eb-990e-ceb216bb0fa4.png)

I dont't know whether the position/amplitude/shape/width of this glitch can meet the requirements, because I have been running for several days without successfully reading the firmware... But when I use the same hardware connection and use JLinkExe to read directly connect, it will pop up " "The chip is secured", so I think the connection is ok. I would be very grateful if you can provide suggestions for glitch here, thank you! ! !

**Comment by cszuo** [comment]
Other boards should also work. Please refer to this https://pbs.twimg.com/media/E1hgeRHX0AEp4Ao?format=jpg&name=large
Make sure your glitch about 20us before the drop in core voltage. Normally, it can succeed within 500 tries in my case.

**Comment by itewqq** [comment]
> Other boards should also work. Please refer to this https://pbs.twimg.com/media/E1hgeRHX0AEp4Ao?format=jpg&name=large
> Make sure your glitch about 20us before the drop in core voltage. Normally, it can succeed within 500 tries in my case.

Thank you so much for the information! 

The last thing I want to confirm is the width and amplitude of glitch. The glitch I chose is 1us in width. I wonder if it must reduce the voltage to 0 in a short time? It seems that my simple mos tube circuit cannot do this.

**Comment by cszuo** [comment]
> > Other boards should also work. Please refer to this https://pbs.twimg.com/media/E1hgeRHX0AEp4Ao?format=jpg&name=large
> > Make sure your glitch about 20us before the drop in core voltage. Normally, it can succeed within 500 tries in my case.
> 
> Thank you so much for the information!
> 
> The last thing I want to confirm is the width and amplitude of glitch. The glitch I chose is 1us in width. I wonder if it must reduce the voltage to 0 in a short time? It seems that my simple mos tube circuit cannot do this.

Hi @itewqq , sorry for late reply, I missed the email somehow. About your question, I didn't change the `width` and `amplitude of glitch`, I directly used the parameters from the code. Like this one https://github.com/pd0wm/airtag-dump/blob/master/src/main.rs#L43

**Comment by itewqq** [comment]
> > > Other boards should also work. Please refer to this https://pbs.twimg.com/media/E1hgeRHX0AEp4Ao?format=jpg&name=large
> > > Make sure your glitch about 20us before the drop in core voltage. Normally, it can succeed within 500 tries in my case.
> > 
> > 
> > Thank you so much for the information!
> > The last thing I want to confirm is the width and amplitude of glitch. The glitch I chose is 1us in width. I wonder if it must reduce the voltage to 0 in a short time? It seems that my simple mos tube circuit cannot do this.
> 
> Hi @itewqq , sorry for late reply, I missed the email somehow. About your question, I didn't change the `width` and `amplitude of glitch`, I directly used the parameters from the code. Like this one https://github.com/pd0wm/airtag-dump/blob/master/src/main.rs#L43

Thank you for the explanation. I found that my problem here is that the mosfet is broken 🤣... I will buy some new mosfets and keep trying. Thank you again!!!
